// Generated by scripts/sync-market-dashboard.mjs. Do not edit by hand.
export const marketSnapshot = {
  "schemaVersion": 1,
  "generatedAt": "2026-09-12T18:54:09.563Z",
  "readOnly": true,
  "summary": {
    "activeListings": 11158,
    "listedValue": 23435.85,
    "medianListPrice": 1.49,
    "paidOrders": 99,
    "soldUnits": 116,
    "salesRevenue": 494.44,
    "averageOrderValue": 4.99,
    "sevenDayRevenue": 0,
    "sevenDayChangePct": -100,
    "unshippedOrders": 1,
    "comparableListings": 1635,
    "marketPremiumPct": 53.4
  },
  "dailySales": [
    {
      "date": "2026-08-14",
      "label": "Aug 14",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-15",
      "label": "Aug 15",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-16",
      "label": "Aug 16",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-17",
      "label": "Aug 17",
      "revenue": 3.99,
      "units": 1
    },
    {
      "date": "2026-08-18",
      "label": "Aug 18",
      "revenue": 55.96,
      "units": 4
    },
    {
      "date": "2026-08-19",
      "label": "Aug 19",
      "revenue": 54.43,
      "units": 7
    },
    {
      "date": "2026-08-20",
      "label": "Aug 20",
      "revenue": 7,
      "units": 1
    },
    {
      "date": "2026-08-21",
      "label": "Aug 21",
      "revenue": 9.46,
      "units": 4
    },
    {
      "date": "2026-08-22",
      "label": "Aug 22",
      "revenue": 64.79,
      "units": 21
    },
    {
      "date": "2026-08-23",
      "label": "Aug 23",
      "revenue": 20.33,
      "units": 17
    },
    {
      "date": "2026-08-24",
      "label": "Aug 24",
      "revenue": 11.97,
      "units": 3
    },
    {
      "date": "2026-08-25",
      "label": "Aug 25",
      "revenue": 10.95,
      "units": 5
    },
    {
      "date": "2026-08-26",
      "label": "Aug 26",
      "revenue": 25.87,
      "units": 13
    },
    {
      "date": "2026-08-27",
      "label": "Aug 27",
      "revenue": 4.48,
      "units": 2
    },
    {
      "date": "2026-08-28",
      "label": "Aug 28",
      "revenue": 3.98,
      "units": 2
    },
    {
      "date": "2026-08-29",
      "label": "Aug 29",
      "revenue": 19.43,
      "units": 7
    },
    {
      "date": "2026-08-30",
      "label": "Aug 30",
      "revenue": 81.04,
      "units": 7
    },
    {
      "date": "2026-08-31",
      "label": "Aug 31",
      "revenue": 25.44,
      "units": 6
    },
    {
      "date": "2026-09-01",
      "label": "Sep 1",
      "revenue": 28.46,
      "units": 4
    },
    {
      "date": "2026-09-02",
      "label": "Sep 2",
      "revenue": 23.43,
      "units": 5
    },
    {
      "date": "2026-09-03",
      "label": "Sep 3",
      "revenue": 10.48,
      "units": 2
    },
    {
      "date": "2026-09-04",
      "label": "Sep 4",
      "revenue": 10.96,
      "units": 4
    },
    {
      "date": "2026-09-05",
      "label": "Sep 5",
      "revenue": 21.99,
      "units": 1
    },
    {
      "date": "2026-09-06",
      "label": "Sep 6",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-09-07",
      "label": "Sep 7",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-09-08",
      "label": "Sep 8",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-09-09",
      "label": "Sep 9",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-09-10",
      "label": "Sep 10",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-09-11",
      "label": "Sep 11",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-09-12",
      "label": "Sep 12",
      "revenue": 0,
      "units": 0
    }
  ],
  "listingValueByGame": [
    {
      "game": "Pokémon",
      "listings": 8067,
      "value": 17224.65
    },
    {
      "game": "Magic: The Gathering",
      "listings": 2127,
      "value": 4229.81
    },
    {
      "game": "One Piece Card Game",
      "listings": 669,
      "value": 1400.34
    },
    {
      "game": "Dragon Ball Super",
      "listings": 207,
      "value": 418.43
    },
    {
      "game": "Yu-Gi-Oh!",
      "listings": 87,
      "value": 160.13
    },
    {
      "game": "Sorcery",
      "listings": 1,
      "value": 2.49
    }
  ],
  "salesByGame": [
    {
      "game": "Pokémon",
      "units": 115,
      "revenue": 492.95
    },
    {
      "game": "Dragon Ball Super",
      "units": 1,
      "revenue": 1.49
    }
  ],
  "marketPosition": {
    "asOf": "2026-09-04",
    "counts": {
      "priced-high": 1425,
      "priced-low": 21,
      "competitive": 189
    },
    "currentDeliveredValue": 5541.27,
    "marketMedianDeliveredValue": 3613.46,
    "methodology": "Latest full active-listing comparison; active comparable listings are directional, not realized sales."
  },
  "sources": {
    "tcgcsv": {
      "sourceId": "tcgcsv",
      "status": "connected",
      "checkedAt": "2026-09-07T14:40:12.419Z",
      "records": 10,
      "detail": "10 supported game catalogs available in the daily cache",
      "error": null
    },
    "pokemonTcgApi": {
      "sourceId": "pokemon-tcg-api",
      "status": "attention",
      "checkedAt": "2026-09-07T14:40:12.451Z",
      "records": 0,
      "detail": "Connection check failed",
      "error": "HTTP 502"
    },
    "scryfall": {
      "sourceId": "scryfall",
      "status": "connected",
      "checkedAt": "2026-09-07T14:40:12.452Z",
      "records": 1,
      "detail": "Exact Magic printing and USD price lookup is reachable",
      "error": null
    }
  },
  "topActive": [
    {
      "sku": "PA-9248",
      "title": "MTG Barbarian Ring 313 ODY Odyssey Foil NM John Avon",
      "price": 41.99,
      "url": "https://www.ebay.com/itm/MTG-Barbarian-Ring-313-ODY-Odyssey-Foil-NM-John-Avon-/158252265035"
    },
    {
      "sku": "PA-9621",
      "title": "Pokemon Eevee 11 Wizards Black Star Promos Holo MP Kagemaru Himeno",
      "price": 36.99,
      "url": "https://www.ebay.com/itm/Pokemon-Eevee-11-Wizards-Black-Star-Promos-Holo-MP-Kagemaru-Himeno-/158275706997"
    },
    {
      "sku": "PA-14420",
      "title": "Pokemon AZ's Tranquility 120/086 Chaos Rising English Holo LP",
      "price": 25.99,
      "url": "https://www.ebay.com/itm/Pokemon-AZ-s-Tranquility-120-086-Chaos-Rising-English-Holo-LP-/158276252201"
    },
    {
      "sku": "4466702",
      "title": "Diglett-Reverse Foil (106) 2002 Pokemon Expedition",
      "price": 24,
      "url": "https://www.ebay.com/itm/Diglett-Reverse-Foil-106-2002-Pokemon-Expedition-/158276265125"
    },
    {
      "sku": "4456390",
      "title": "Feraligatr-Holo (160) 2000 Pokemon Japanese Neo",
      "price": 21,
      "url": "https://www.ebay.com/itm/Feraligatr-Holo-160-2000-Pokemon-Japanese-Neo-/158275857963"
    },
    {
      "sku": "PA-3642",
      "title": "Pokemon Chansey File No.113 Bandai Carddass Pocket Monsters Japanese MP",
      "price": 20.99,
      "url": "https://www.ebay.com/itm/Pokemon-Chansey-File-No-113-Bandai-Carddass-Pocket-Monsters-Japanese-MP-/158220855058"
    },
    {
      "sku": "PA-13395",
      "title": "Magic MTG Decree of Justice SCG 8 Scourge Non-Foil NM",
      "price": 20.49,
      "url": "https://www.ebay.com/itm/Magic-MTG-Decree-of-Justice-SCG-8-Scourge-Non-Foil-NM-/158269842585"
    },
    {
      "sku": "PA-4147",
      "title": "Yu-Gi-Oh Blue-Eyes White Dragon FL1-EN001 Limited Edition Secret Rare LP",
      "price": 19.99,
      "url": "https://www.ebay.com/itm/Yu-Gi-Oh-Blue-Eyes-White-Dragon-FL1-EN001-Limited-Edition-Secret-Rare-LP-/158234533005"
    }
  ]
} as const;
