// Generated by scripts/sync-market-dashboard.mjs. Do not edit by hand.
export const marketSnapshot = {
  "schemaVersion": 1,
  "generatedAt": "2026-09-07T17:41:02.339Z",
  "readOnly": true,
  "summary": {
    "activeListings": 9628,
    "listedValue": 16642.72,
    "medianListPrice": 1.49,
    "paidOrders": 99,
    "soldUnits": 116,
    "salesRevenue": 494.44,
    "averageOrderValue": 4.99,
    "sevenDayRevenue": 95.32,
    "sevenDayChangePct": -44.3,
    "unshippedOrders": 1,
    "comparableListings": 1645,
    "marketPremiumPct": 51.9
  },
  "dailySales": [
    {
      "date": "2026-08-09",
      "label": "Aug 9",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-10",
      "label": "Aug 10",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-11",
      "label": "Aug 11",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-12",
      "label": "Aug 12",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-13",
      "label": "Aug 13",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-14",
      "label": "Aug 14",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-15",
      "label": "Aug 15",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-16",
      "label": "Aug 16",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-08-17",
      "label": "Aug 17",
      "revenue": 3.99,
      "units": 1
    },
    {
      "date": "2026-08-18",
      "label": "Aug 18",
      "revenue": 55.96,
      "units": 4
    },
    {
      "date": "2026-08-19",
      "label": "Aug 19",
      "revenue": 54.43,
      "units": 7
    },
    {
      "date": "2026-08-20",
      "label": "Aug 20",
      "revenue": 7,
      "units": 1
    },
    {
      "date": "2026-08-21",
      "label": "Aug 21",
      "revenue": 9.46,
      "units": 4
    },
    {
      "date": "2026-08-22",
      "label": "Aug 22",
      "revenue": 64.79,
      "units": 21
    },
    {
      "date": "2026-08-23",
      "label": "Aug 23",
      "revenue": 20.33,
      "units": 17
    },
    {
      "date": "2026-08-24",
      "label": "Aug 24",
      "revenue": 11.97,
      "units": 3
    },
    {
      "date": "2026-08-25",
      "label": "Aug 25",
      "revenue": 10.95,
      "units": 5
    },
    {
      "date": "2026-08-26",
      "label": "Aug 26",
      "revenue": 25.87,
      "units": 13
    },
    {
      "date": "2026-08-27",
      "label": "Aug 27",
      "revenue": 4.48,
      "units": 2
    },
    {
      "date": "2026-08-28",
      "label": "Aug 28",
      "revenue": 3.98,
      "units": 2
    },
    {
      "date": "2026-08-29",
      "label": "Aug 29",
      "revenue": 19.43,
      "units": 7
    },
    {
      "date": "2026-08-30",
      "label": "Aug 30",
      "revenue": 81.04,
      "units": 7
    },
    {
      "date": "2026-08-31",
      "label": "Aug 31",
      "revenue": 25.44,
      "units": 6
    },
    {
      "date": "2026-09-01",
      "label": "Sep 1",
      "revenue": 28.46,
      "units": 4
    },
    {
      "date": "2026-09-02",
      "label": "Sep 2",
      "revenue": 23.43,
      "units": 5
    },
    {
      "date": "2026-09-03",
      "label": "Sep 3",
      "revenue": 10.48,
      "units": 2
    },
    {
      "date": "2026-09-04",
      "label": "Sep 4",
      "revenue": 10.96,
      "units": 4
    },
    {
      "date": "2026-09-05",
      "label": "Sep 5",
      "revenue": 21.99,
      "units": 1
    },
    {
      "date": "2026-09-06",
      "label": "Sep 6",
      "revenue": 0,
      "units": 0
    },
    {
      "date": "2026-09-07",
      "label": "Sep 7",
      "revenue": 0,
      "units": 0
    }
  ],
  "listingValueByGame": [
    {
      "game": "Pokémon",
      "listings": 7131,
      "value": 12673.19
    },
    {
      "game": "Magic: The Gathering",
      "listings": 1698,
      "value": 2602.02
    },
    {
      "game": "One Piece Card Game",
      "listings": 503,
      "value": 782.97
    },
    {
      "game": "Dragon Ball Super",
      "listings": 208,
      "value": 421.92
    },
    {
      "game": "Yu-Gi-Oh!",
      "listings": 87,
      "value": 160.13
    },
    {
      "game": "Sorcery",
      "listings": 1,
      "value": 2.49
    }
  ],
  "salesByGame": [
    {
      "game": "Pokémon",
      "units": 115,
      "revenue": 492.95
    },
    {
      "game": "Dragon Ball Super",
      "units": 1,
      "revenue": 1.49
    }
  ],
  "marketPosition": {
    "asOf": "2026-09-04",
    "counts": {
      "priced-high": 1432,
      "priced-low": 22,
      "competitive": 191
    },
    "currentDeliveredValue": 5631.85,
    "marketMedianDeliveredValue": 3708.55,
    "methodology": "Latest full active-listing comparison; active comparable listings are directional, not realized sales."
  },
  "sources": {
    "tcgcsv": {
      "sourceId": "tcgcsv",
      "status": "connected",
      "checkedAt": "2026-09-07T14:40:12.419Z",
      "records": 10,
      "detail": "10 supported game catalogs available in the daily cache",
      "error": null
    },
    "pokemonTcgApi": {
      "sourceId": "pokemon-tcg-api",
      "status": "attention",
      "checkedAt": "2026-09-07T14:40:12.451Z",
      "records": 0,
      "detail": "Connection check failed",
      "error": "HTTP 502"
    },
    "scryfall": {
      "sourceId": "scryfall",
      "status": "connected",
      "checkedAt": "2026-09-07T14:40:12.452Z",
      "records": 1,
      "detail": "Exact Magic printing and USD price lookup is reachable",
      "error": null
    }
  },
  "topActive": [
    {
      "sku": "PA-9248",
      "title": "MTG Barbarian Ring 313 ODY Odyssey Foil NM John Avon",
      "price": 41.99,
      "url": "https://www.ebay.com/itm/MTG-Barbarian-Ring-313-ODY-Odyssey-Foil-NM-John-Avon-/158252265035"
    },
    {
      "sku": "PA-9621",
      "title": "Pokemon Eevee 11 Wizards Black Star Promos Holo MP Kagemaru Himeno",
      "price": 36.99,
      "url": "https://www.ebay.com/itm/Pokemon-Eevee-11-Wizards-Black-Star-Promos-Holo-MP-Kagemaru-Himeno-/158255793701"
    },
    {
      "sku": "PA-10647",
      "title": "Pokemon Eevee 0407/07 CBB4C S-Chinese Full Art NM Narumi Sato",
      "price": 25.49,
      "url": "https://www.ebay.com/itm/Pokemon-Eevee-0407-07-CBB4C-S-Chinese-Full-Art-NM-Narumi-Sato-/158262926481"
    },
    {
      "sku": "PA-10503",
      "title": "Pokemon Clefairy 094/088 Perfect Order Holo NM Cona Nitanda",
      "price": 22.99,
      "url": "https://www.ebay.com/itm/Pokemon-Clefairy-094-088-Perfect-Order-Holo-NM-Cona-Nitanda-/158261219817"
    },
    {
      "sku": "PA-11622",
      "title": "Pokemon Diglett 106/165 Expedition Base Set Reverse Holo MP Masako Yamashita",
      "price": 21.99,
      "url": "https://www.ebay.com/itm/Pokemon-Diglett-106-165-Expedition-Base-Set-Reverse-Holo-MP-Masako-Yamashita-/158265511981"
    },
    {
      "sku": "PA-3642",
      "title": "Pokemon Chansey File No.113 Bandai Carddass Pocket Monsters Japanese MP",
      "price": 20.99,
      "url": "https://www.ebay.com/itm/Pokemon-Chansey-File-No-113-Bandai-Carddass-Pocket-Monsters-Japanese-MP-/158220855058"
    },
    {
      "sku": "PA-4147",
      "title": "Yu-Gi-Oh Blue-Eyes White Dragon FL1-EN001 Limited Edition Secret Rare LP",
      "price": 19.99,
      "url": "https://www.ebay.com/itm/Yu-Gi-Oh-Blue-Eyes-White-Dragon-FL1-EN001-Limited-Edition-Secret-Rare-LP-/158234533005"
    },
    {
      "sku": "BND-20260904-06",
      "title": "Pokemon VMAX Climax Korean Holo 10 Card Lot NM Exact Cards",
      "price": 19.99,
      "url": "https://www.ebay.com/itm/Pokemon-VMAX-Climax-Korean-Holo-10-Card-Lot-NM-Exact-Cards-/158257827490"
    }
  ]
} as const;
