// Generated by scripts/sync-ingestion-dashboard.mjs.
export const ingestionSnapshot = {
  "schemaVersion": 1,
  "batchId": "No batch loaded",
  "createdAt": null,
  "publishMode": "DRAFT_ONLY",
  "summary": {
    "AUTO_DRAFT": 0,
    "REVIEW": 0,
    "RESCAN": 0,
    "CONFLICT": 0
  },
  "cards": []
} as const;
